# ZuluSCSI™ - Copyright (c) 2024 Rabbit Hole Computing
#
# ZuluSCSI™ file is licensed under the GPL version 3 or any later version. 
#
# https://www.gnu.org/licenses/gpl-3.0.html
# ----
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details. 
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Build ZuluSCSI firmware

on: 
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build_firmware:
#    name: RHC-internal-Z4
#    runs-on: self-hosted
    name: Build firmware on Ubuntu 22.04
    runs-on: ubuntu-22.04
    
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          path: ZuluSCSI
          fetch-depth: "0"
      
      - name: Install platformio
        run: |
          pip install -U platformio
      
      - name: Build firmware
        run: |
          cd ZuluSCSI
          pio run -v
      
      - name: Rename firmware files
        run: |
          cd ZuluSCSI
          tools/rename_binaries.sh

      - name: Upload binaries into build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ZuluSCSI/distrib/*
          name: ZuluSCSI binaries
      
      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
        run: |
          cd ZuluSCSI
          git tag -d latest
          git tag latest
          git push origin --force latest
          cd distrib
          rm -rf bootloader
          gh api repos/${GITHUB_REPOSITORY}/releases/tags/latest | jq -r '.assets[] | [.url] | @tsv' | xargs -n 1 gh api -X DELETE || true
          gh release upload --repo ${GITHUB_REPOSITORY} --clobber latest *

      - name: Upload to newly created release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          cd ZuluSCSI
          tools/rename_firmware_for_release.sh
          cd distrib
          rm -rf bootloader
          RELEASE=$(basename ${{github.ref}})
          gh release upload --repo ${GITHUB_REPOSITORY} $RELEASE *.bin *.uf2
